a=[]
student1=int(input("enter student marks"))
a.append(student1)
student2=int(input("enter student marks"))
a.append(student2)
student3=int(input("enter student marks"))
a.append(student3)
student4=int(input("enter student marks"))
a.append(student4)
student5=int(input("enter student marks"))
a.append(student5)
student6=int(input("enter student marks"))
a.append(student6)
print(a)
a.sort()
print(a)